### ISSUE TITLE
My metamask is compromised, I got only two days after that my funds are coming out from the pool, that was done by the hacker, I added funds but the hacker is using or a flashbot or sweeper. Can someone help me with this issue before I lose everything? Thanks in advance.

### ISSUE THREAD

**Issue by ZerOne777** [flashbots/pm#102]

**Comment by terorie** [comment]
Flashbots has a whitehat team for recovering funds, as documented on their page.

- https://docs.flashbots.net/whitehat/
- https://whitehat.flashbots.net/

Please don't spam GitHub issues. This will not speed things up since it mostly pings people that have nothing to do with Flashbots (such as me, I cannot do anything). I hope you are able to reach the right people to recover your funds and wish you the best of luck.
